### ISSUE TITLE
problems with non-modal dialogs

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/joist#293]
Noted while reviewing #166.

These problem occur in master, as of joist 4c143a8e9037d3d8c97eb2601634d1a0e116a137. They can be demonstrated by running the joist demo application (joist/joist_en.hmtl).  Note that the demo currently contains 2 instances of DialogsDemoView, so that you can test switching between screens.

A non-modal dialog may be global (if created by the PhET menu) or specific to a screen (if created by the screen).  

Problems with the current implementation non-modal dialogs:

(1) The close button does not work.

(2) For screen-specific non-modal dialogs, behavior when switching screens is incorrect. When switching screens, dialogs should disappear along with screen. When returning to a screen, dialogs specific to that screen should be restored.  Currently, dialogs remain on the screen regardless of which screen is selected.

(3) Non-modal dialogs should be positionable. They are currently limited to centered on the screen.

(4) Non-modal dialogs should be movable, so that you can interact with other UI components. Their position is currently fixed.

(5) Placement of the close button can overlap with the dialog content. See screenshot below. This problem may not be limited to non-modal dialogs (untested with modal dialogs).

![screenshot_578](https://cloud.githubusercontent.com/assets/3046552/9368069/8a7db4a6-467e-11e5-98c8-abee471def13.png)

Assigned to @jonathanolson, the author of Dialog.

**Comment by pixelzoom** [comment]
Let's put an assertion in for now that bails if `modal:false`, until we can get around to addressing this.

**Comment by pixelzoom** [comment]
In https://github.com/phetsims/joist/issues/166#issuecomment-133016415, @jonathanolson asked:
> is there a good use-case for non-centered?

Any non-modal dialog. (And any API I've ever worked with that supports dialogs.)

**Comment by pixelzoom** [comment]
@jonathanolson will add the assertion,

**Comment by samreid** [comment]
I fixed the "close button will not work" problem in https://github.com/phetsims/joist/issues/314.

**Comment by pixelzoom** [comment]
Issue 5 (placement of close button) is describe in more detail in https://github.com/phetsims/joist/issues/346, and is not specific to non-modal Dialogs.

**Comment by pixelzoom** [comment]
Issues 2-5 are still problems.

**Comment by pixelzoom** [comment]
3/29/18 dev meeting: @andrea-phet and I will triage this issue.

**Comment by pixelzoom** [comment]
Dialog was recent giving a major overhaul.  While still not ideal, it's better.  It does not support non-modal dialogs (`modal: false`) and there are currently no PhET sims with non-modal dialogs.  So I'm going to close this issue.  If/when PhET needs non-modal dialogs, we can create a new issue "support non-modal dialogs".

**Comment by samreid** [comment]
There are still TODOs marked for this issue, discovered during https://github.com/phetsims/chipper/issues/946

**Comment by zepumph** [comment]
Removed the TODO over in https://github.com/phetsims/ratio-and-proportion/issues/509 by moving the pdomVisibility stuff directly into Sim. Closing
